### ISSUE TITLE
Non-rewindable iterators

### ISSUE THREAD

**Issue by ostrolucky** [PatchRanger/cartesian-iterator#4]
So, this library does rewinds, which is not possible in some cases, like following

```php
$cartesianIterator = new CartesianIterator();
$gen1 = function() {
    yield 1;
    yield 2;
};
$gen2 = function() {
    yield 3;
    yield 4;
};

$cartesianIterator->attachIterator($gen1());
$cartesianIterator->attachIterator($gen2());

iterator_to_array($cartesianIterator);
```

results in
```
PHP Fatal error:  Uncaught Exception: Cannot rewind a generator that was already run in /Users/gostrolucky/PhpstormProjects/cartesian-iterator/src/CartesianIterator.php:73
Stack trace:
#0 /Users/gostrolucky/PhpstormProjects/cartesian-iterator/src/CartesianIterator.php(73): Generator->rewind()
#1 /Users/gostrolucky/PhpstormProjects/cartesian-iterator/src/CartesianIterator.php(58): PatchRanger\CartesianIterator->applyNext()
#2 [internal function]: PatchRanger\CartesianIterator->next()
#3 /Users/gostrolucky/PhpstormProjects/cartesian-iterator/test.php(32): iterator_to_array(Object(PatchRanger\CartesianIterator))
#4 {main}
  thrown in /Users/gostrolucky/PhpstormProjects/cartesian-iterator/src/CartesianIterator.php on line 73

Fatal error: Uncaught Exception: Cannot rewind a generator that was already run in /Users/gostrolucky/PhpstormProjects/cartesian-iterator/src/CartesianIterator.php on line 73

Exception: Cannot rewind a generator that was already run in /Users/gostrolucky/PhpstormProjects/cartesian-iterator/src/CartesianIterator.php on line 73

Call Stack:
    0.0006     400464   1. {main}() /Users/gostrolucky/PhpstormProjects/cartesian-iterator/test.php:0
    0.0111     671112   2. iterator_to_array() /Users/gostrolucky/PhpstormProjects/cartesian-iterator/test.php:32
    0.0112     672352   3. PatchRanger\CartesianIterator->next() /Users/gostrolucky/PhpstormProjects/cartesian-iterator/test.php:32
    0.0112     672352   4. PatchRanger\CartesianIterator->applyNext() /Users/gostrolucky/PhpstormProjects/cartesian-iterator/src/CartesianIterator.php:58
    0.0112     672240   5. Generator->rewind() /Users/gostrolucky/PhpstormProjects/cartesian-iterator/src/CartesianIterator.php:73
```

Do you have some idea how to solve this problem?

**Comment by PatchRanger** [comment]
You're right, that's indeed a problem - and I don't have a solution (or even "a drawing of a key") for now: relying on rewinds makes this library deadly simple, fast and memory efficient, I am working on benchmark https://github.com/PatchRanger/php-cartesian-benchmark to showcase this statement. I guess, it could be workarounded by https://github.com/JeroenDeDauw/RewindableGenerator or similar.

**Comment by ostrolucky** [comment]
Huh, didn't know about these. Why not have a benchmark as part of this repo though?

**Comment by PatchRanger** [comment]
Modularity) Benchmark-related stuff is not needed for those who need the iterator only, I prefer to keep them separate.

**Comment by ostrolucky** [comment]
You know require-dev dependencies are not shipped to end user right? You can even exclude files you don't want to distribute
